CI: Workaround rustup race condition with two parallel cargo commands
Rust is normally installed automatically but there is currently a race
condition that causes installation failures when Ninja runs two CARGO
commands in parallel. Workaround that by running a dummy cargo command
first that installs the toolchain before starting the build system.

Perhaps this should be somehow represented in the generated build.ninja,
e.g. using an "order-only dependency" (with || instead of |) that
runs a dummy Rust command before starting any CARGO commands in
parallel. This would probably require some changes in Ninjapie...

[1949/5236] CARGO build/hw-riscv-release/rust/riscv64imc-unknown-none-elf/release/blau build/hw-riscv-release/rust/riscv64imc-unknown-none-elf/release/brom build/hw-riscv-release/rust/riscv64imc-unknown-none-elf/release/rosa
FAILED: build/hw-riscv-release/rust/riscv64imc-unknown-none-elf/release/blau build/hw-riscv-release/rust/riscv64imc-unknown-none-elf/release/brom build/hw-riscv-release/rust/riscv64imc-unknown-none-elf/release/rosa
cd ./src/rot &&  cargo build --color=always -q --release -Z build-std=core,alloc --target riscv64imc-unknown-none-elf --features base/hw --target-dir "/home/runner/work/M3/M3/build/hw-riscv-release/rust"
info: syncing channel updates for 'nightly-2023-12-01-x86_64-unknown-linux-gnu'
info: latest update on 2023-12-01, rust version 1.76.0-nightly (87e1447aa 2023-11-30)
info: downloading component 'cargo'
error: component download failed for cargo-x86_64-unknown-linux-gnu: could not rename downloaded file from '/home/runner/work/M3/M3/.rustup/downloads/2731162802187220803c79a9cf886f13733744bc86bc5959dc44116fdfddfa6f.partial' to '/home/runner/work/M3/M3/.rustup/downloads/2731162802187220803c79a9cf886f13733744bc86bc5959dc44116fdfddfa6f'
[1950/5236] LINK build/hw-riscv-release/src/apps/allocator/allocator
[1951/5236] CARGO build/hw-riscv-release/rust/riscv64-linux-m3-muslsf/release/libtilemux.a
info: syncing channel updates for 'nightly-2023-12-01-x86_64-unknown-linux-gnu'
info: latest update on 2023-12-01, rust version 1.76.0-nightly (87e1447aa 2023-11-30)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'llvm-tools'
info: downloading component 'rust-docs'
info: downloading component 'rust-src'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'llvm-tools'
info: installing component 'rust-docs'
info: installing component 'rust-src'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'