Update to Rust nightly-2024-02-03
error: data-layout for target `arm-linux-m3-musleabisf`,
 `e-m:e-p:32:32-i1:8:32-i8:8:32-i16:16:32-i64:64-v128:64:128-a:0:32-n32-S64`,
 differs from LLVM target's `armv7-unknown-linux-gnueabi` default layout,
 `e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64`

warning: shared reference of mutable static is discouraged
   --> apps/rustunittests/src/tmgate.rs:134:33
    |
134 |         VirtAddr::from(unsafe { &_OBJ as *const _ })
    |                                 ^^^^^ shared reference of mutable static
    |
    = note: for more information, see issue 114447
    = note: reference of mutable static is a hard error from 2024 edition
    = note: mutable statics can be written to by multiple threads: aliasing violations or data races will cause undefined behavior
    = note: `#[warn(static_mut_ref)]` on by default
help: shared references are dangerous since if there's any kind of mutation of that static while the reference lives, that's UB; use `addr_of!` instead to create a raw pointer
    |
134 |         VirtAddr::from(unsafe { addr_of!(_OBJ) as *const _ })
    |                                 ~~~~~~~~~~~~~~